import Navbr from './components/naveBr/page'
import Footer from './components/footer/page'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })


import { Mulish } from 'next/font/google'
 
const mulish = Mulish({
  weight: ['300', '400','500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
})  


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={mulish.className}>
      <Navbr />
        {children}
        </body>
    </html>
  )
}
